import React from "react";

const MenuItems = [
  {
    icon: <i class="side-menu__icon fa fa-user-plus"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    title: "Patients",
    class: "",
    color: "",
    badgetxt: "",
    path: `${import.meta.env.BASE_URL}patients`,
    roles: ['Nurse','Doctor'],
    condition: false,
  },  
  {
    icon: <i class="side-menu__icon fa fa-map-signs"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    title: "Visits",
    class: "",
    color: "",
    badgetxt: "",
    path: `${import.meta.env.BASE_URL}visits`,
    roles: ['Nurse','Doctor'],
    condition: false,
  },
  {
    icon: <i class="side-menu__icon fa fa-heartbeat"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    title: "Insurance",
    class: "",
    color: "",
    badgetxt: "",
    path: `${import.meta.env.BASE_URL}insurance`,
    roles: ['Doctor'],
    condition: false,
  },
  {
    icon: <i class="side-menu__icon fa fa-sitemap"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    title: "Department",
    class: "",
    color: "",
    badgetxt: "",
    path: `${import.meta.env.BASE_URL}Department`,
    roles: ['Doctor'],
    condition: false,
  },
  {
    icon: <i class="side-menu__icon fa fa-unlock-alt"></i>,
    type: "sub",
    Name: "",
    active: false,
    selected: false,
    title: "Access Control",
    class: "",
    color: "",
    badgetxt: "",
    path: `${import.meta.env.BASE_URL}access-control`,
    roles: ['Doctor'],
    condition: false,
  },
]
export default MenuItems;
